CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Categories" (
    "CategoryID" integer GENERATED BY DEFAULT AS IDENTITY,
    "CategoryName" text NOT NULL,
    CONSTRAINT "PK_Categories" PRIMARY KEY ("CategoryID")
);

CREATE TABLE "Markets" (
    "MarketID" integer GENERATED BY DEFAULT AS IDENTITY,
    "MarketName" text NOT NULL,
    "City" text NOT NULL,
    "Region" text,
    CONSTRAINT "PK_Markets" PRIMARY KEY ("MarketID")
);

CREATE TABLE "SourceTypes" (
    "SourceTypeID" integer GENERATED BY DEFAULT AS IDENTITY,
    "SourceName" text NOT NULL,
    "Description" text,
    CONSTRAINT "PK_SourceTypes" PRIMARY KEY ("SourceTypeID")
);

CREATE TABLE "Users" (
    "UserID" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Email" text NOT NULL,
    "AvatarStr" text NOT NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("UserID")
);

CREATE TABLE "Products" (
    "ProductID" integer GENERATED BY DEFAULT AS IDENTITY,
    "CategoryID" integer NOT NULL,
    "StandardName" text NOT NULL,
    "Description" text,
    "BaseUnit" text NOT NULL,
    CONSTRAINT "PK_Products" PRIMARY KEY ("ProductID"),
    CONSTRAINT "FK_Products_Categories_CategoryID" FOREIGN KEY ("CategoryID") REFERENCES "Categories" ("CategoryID")
);

CREATE TABLE "PriceForecasts" (
    "ForecastID" bigint GENERATED BY DEFAULT AS IDENTITY,
    "ProductID" integer NOT NULL,
    "MarketID" integer NOT NULL,
    "ForecastDate" timestamp with time zone NOT NULL,
    "PredictedAvgPrice" numeric(18,2) NOT NULL,
    "ConfidenceScore" numeric(5,2),
    "Recommendation" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_PriceForecasts" PRIMARY KEY ("ForecastID"),
    CONSTRAINT "FK_PriceForecasts_Markets_MarketID" FOREIGN KEY ("MarketID") REFERENCES "Markets" ("MarketID"),
    CONSTRAINT "FK_PriceForecasts_Products_ProductID" FOREIGN KEY ("ProductID") REFERENCES "Products" ("ProductID")
);

CREATE TABLE "PriceLogs" (
    "PriceLogID" bigint GENERATED BY DEFAULT AS IDENTITY,
    "ProductID" integer NOT NULL,
    "MarketID" integer NOT NULL,
    "SourceTypeID" integer NOT NULL,
    "ReportDate" timestamp with time zone NOT NULL,
    "MinPrice" numeric(18,2),
    "MaxPrice" numeric(18,2),
    "AvgPrice" numeric(18,2) NOT NULL,
    "ReportedUnit" text NOT NULL,
    "StandardizedPricePerKg" numeric(18,2) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_PriceLogs" PRIMARY KEY ("PriceLogID"),
    CONSTRAINT "FK_PriceLogs_Markets_MarketID" FOREIGN KEY ("MarketID") REFERENCES "Markets" ("MarketID"),
    CONSTRAINT "FK_PriceLogs_Products_ProductID" FOREIGN KEY ("ProductID") REFERENCES "Products" ("ProductID"),
    CONSTRAINT "FK_PriceLogs_SourceTypes_SourceTypeID" FOREIGN KEY ("SourceTypeID") REFERENCES "SourceTypes" ("SourceTypeID")
);

CREATE TABLE "ProductAliases" (
    "AliasID" integer GENERATED BY DEFAULT AS IDENTITY,
    "OriginalName" text NOT NULL,
    "SourceTypeID" integer NOT NULL,
    "ProductID" integer NOT NULL,
    CONSTRAINT "PK_ProductAliases" PRIMARY KEY ("AliasID"),
    CONSTRAINT "FK_ProductAliases_Products_ProductID" FOREIGN KEY ("ProductID") REFERENCES "Products" ("ProductID"),
    CONSTRAINT "FK_ProductAliases_SourceTypes_SourceTypeID" FOREIGN KEY ("SourceTypeID") REFERENCES "SourceTypes" ("SourceTypeID")
);

CREATE TABLE "SavingsLogs" (
    "SavingsLogID" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserID" integer NOT NULL,
    "ProductID" integer NOT NULL,
    "Date" timestamp with time zone NOT NULL,
    "SavedAmount" numeric(18,2) NOT NULL,
    "KilosBought" numeric(18,2) NOT NULL,
    CONSTRAINT "PK_SavingsLogs" PRIMARY KEY ("SavingsLogID"),
    CONSTRAINT "FK_SavingsLogs_Products_ProductID" FOREIGN KEY ("ProductID") REFERENCES "Products" ("ProductID") ON DELETE CASCADE,
    CONSTRAINT "FK_SavingsLogs_Users_UserID" FOREIGN KEY ("UserID") REFERENCES "Users" ("UserID") ON DELETE CASCADE
);

CREATE TABLE "UserFavorites" (
    "FavoriteID" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserID" integer NOT NULL,
    "ProductID" integer NOT NULL,
    "MarketID" integer NOT NULL,
    CONSTRAINT "PK_UserFavorites" PRIMARY KEY ("FavoriteID"),
    CONSTRAINT "FK_UserFavorites_Markets_MarketID" FOREIGN KEY ("MarketID") REFERENCES "Markets" ("MarketID") ON DELETE CASCADE,
    CONSTRAINT "FK_UserFavorites_Products_ProductID" FOREIGN KEY ("ProductID") REFERENCES "Products" ("ProductID") ON DELETE CASCADE,
    CONSTRAINT "FK_UserFavorites_Users_UserID" FOREIGN KEY ("UserID") REFERENCES "Users" ("UserID") ON DELETE CASCADE
);

CREATE UNIQUE INDEX "IX_Categories_CategoryName" ON "Categories" ("CategoryName");

CREATE INDEX "IX_PriceForecasts_MarketID" ON "PriceForecasts" ("MarketID");

CREATE INDEX "IX_PriceForecasts_ProductID_ForecastDate" ON "PriceForecasts" ("ProductID", "ForecastDate");

CREATE INDEX "IX_PriceLogs_MarketID" ON "PriceLogs" ("MarketID");

CREATE INDEX "IX_PriceLogs_ProductID_ReportDate" ON "PriceLogs" ("ProductID", "ReportDate");

CREATE INDEX "IX_PriceLogs_SourceTypeID" ON "PriceLogs" ("SourceTypeID");

CREATE UNIQUE INDEX "IX_ProductAliases_OriginalName_SourceTypeID" ON "ProductAliases" ("OriginalName", "SourceTypeID");

CREATE INDEX "IX_ProductAliases_ProductID" ON "ProductAliases" ("ProductID");

CREATE INDEX "IX_ProductAliases_SourceTypeID" ON "ProductAliases" ("SourceTypeID");

CREATE INDEX "IX_Products_CategoryID" ON "Products" ("CategoryID");

CREATE UNIQUE INDEX "IX_Products_StandardName" ON "Products" ("StandardName");

CREATE INDEX "IX_SavingsLogs_ProductID" ON "SavingsLogs" ("ProductID");

CREATE INDEX "IX_SavingsLogs_UserID" ON "SavingsLogs" ("UserID");

CREATE UNIQUE INDEX "IX_SourceTypes_SourceName" ON "SourceTypes" ("SourceName");

CREATE INDEX "IX_UserFavorites_MarketID" ON "UserFavorites" ("MarketID");

CREATE INDEX "IX_UserFavorites_ProductID" ON "UserFavorites" ("ProductID");

CREATE UNIQUE INDEX "IX_UserFavorites_UserID_ProductID_MarketID" ON "UserFavorites" ("UserID", "ProductID", "MarketID");

CREATE UNIQUE INDEX "IX_Users_Email" ON "Users" ("Email");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260402020015_InitialPostgres', '8.0.10');

COMMIT;

