// <auto-generated />
using System;
using AgroForecast.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AgroForecast.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AgroForecast.Domain.Entities.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CategoryID"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CategoryID");

                    b.HasIndex("CategoryName")
                        .IsUnique();

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("AgroForecast.Domain.Entities.Market", b =>
                {
                    b.Property<int>("MarketID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MarketID"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MarketName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Region")
                        .HasColumnType("text");

                    b.HasKey("MarketID");

                    b.ToTable("Markets");
                });

            modelBuilder.Entity("AgroForecast.Domain.Entities.PriceForecast", b =>
                {
                    b.Property<long>("ForecastID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ForecastID"));

                    b.Property<decimal?>("ConfidenceScore")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ForecastDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MarketID")
                        .HasColumnType("integer");

                    b.Property<decimal>("PredictedAvgPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("ProductID")
                        .HasColumnType("integer");

                    b.Property<string>("Recommendation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ForecastID");

                    b.HasIndex("MarketID");

                    b.HasIndex("ProductID", "ForecastDate");

                    b.ToTable("PriceForecasts");
                });

            modelBuilder.Entity("AgroForecast.Domain.Entities.PriceLog", b =>
                {
                    b.Property<long>("PriceLogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("PriceLogID"));

                    b.Property<decimal>("AvgPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MarketID")
                        .HasColumnType("integer");

                    b.Property<decimal?>("MaxPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("MinPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("ProductID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ReportDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReportedUnit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SourceTypeID")
                        .HasColumnType("integer");

                    b.Property<decimal>("StandardizedPricePerKg")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("PriceLogID");

                    b.HasIndex("MarketID");

                    b.HasIndex("SourceTypeID");

                    b.HasIndex("ProductID", "ReportDate");

                    b.ToTable("PriceLogs");
                });

            modelBuilder.Entity("AgroForecast.Domain.Entities.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProductID"));

                    b.Property<string>("BaseUnit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CategoryID")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("StandardName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ProductID");

                    b.HasIndex("CategoryID");

                    b.HasIndex("StandardName")
                        .IsUnique();

                    b.ToTable("Products");
                });

            modelBuilder.Entity("AgroForecast.Domain.Entities.ProductAlias", b =>
                {
                    b.Property<int>("AliasID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AliasID"));

                    b.Property<string>("OriginalName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProductID")
                        .HasColumnType("integer");

                    b.Property<int>("SourceTypeID")
                        .HasColumnType("integer");

                    b.HasKey("AliasID");

                    b.HasIndex("ProductID");

                    b.HasIndex("SourceTypeID");

                    b.HasIndex("OriginalName", "SourceTypeID")
                        .IsUnique();

                    b.ToTable("ProductAliases");
                });

            modelBuilder.Entity("AgroForecast.Domain.Entities.SavingsLog", b =>
                {
                    b.Property<int>("SavingsLogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SavingsLogID"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("KilosBought")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("ProductID")
                        .HasColumnType("integer");

                    b.Property<decimal>("SavedAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.HasKey("SavingsLogID");

                    b.HasIndex("ProductID");

                    b.HasIndex("UserID");

                    b.ToTable("SavingsLogs");
                });

            modelBuilder.Entity("AgroForecast.Domain.Entities.SourceType", b =>
                {
                    b.Property<int>("SourceTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SourceTypeID"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SourceTypeID");

                    b.HasIndex("SourceName")
                        .IsUnique();

                    b.ToTable("SourceTypes");
                });

            modelBuilder.Entity("AgroForecast.Domain.Entities.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserID"));

                    b.Property<string>("AvatarStr")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AgroForecast.Domain.Entities.UserFavorite", b =>
                {
                    b.Property<int>("FavoriteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FavoriteID"));

                    b.Property<int>("MarketID")
                        .HasColumnType("integer");

                    b.Property<int>("ProductID")
                        .HasColumnType("integer");

                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.HasKey("FavoriteID");

                    b.HasIndex("MarketID");

                    b.HasIndex("ProductID");

                    b.HasIndex("UserID", "ProductID", "MarketID")
                        .IsUnique();

                    b.ToTable("UserFavorites");
                });

            modelBuilder.Entity("AgroForecast.Domain.Entities.PriceForecast", b =>
                {
                    b.HasOne("AgroForecast.Domain.Entities.Market", "Market")
                        .WithMany("PriceForecasts")
                        .HasForeignKey("MarketID")
                        .IsRequired();

                    b.HasOne("AgroForecast.Domain.Entities.Product", "Product")
                        .WithMany("PriceForecasts")
                        .HasForeignKey("ProductID")
                        .IsRequired();

                    b.Navigation("Market");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("AgroForecast.Domain.Entities.PriceLog", b =>
                {
                    b.HasOne("AgroForecast.Domain.Entities.Market", "Market")
                        .WithMany("PriceLogs")
                        .HasForeignKey("MarketID")
                        .IsRequired();

                    b.HasOne("AgroForecast.Domain.Entities.Product", "Product")
                        .WithMany("PriceLogs")
                        .HasForeignKey("ProductID")
                        .IsRequired();

                    b.HasOne("AgroForecast.Domain.Entities.SourceType", "SourceType")
                        .WithMany("PriceLogs")
                        .HasForeignKey("SourceTypeID")
                        .IsRequired();

                    b.Navigation("Market");

                    b.Navigation("Product");

                    b.Navigation("SourceType");
                });

            modelBuilder.Entity("AgroForecast.Domain.Entities.Product", b =>
                {
                    b.HasOne("AgroForecast.Domain.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryID")
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("AgroForecast.Domain.Entities.ProductAlias", b =>
                {
                    b.HasOne("AgroForecast.Domain.Entities.Product", "Product")
                        .WithMany("ProductAliases")
                        .HasForeignKey("ProductID")
                        .IsRequired();

                    b.HasOne("AgroForecast.Domain.Entities.SourceType", "SourceType")
                        .WithMany("ProductAliases")
                        .HasForeignKey("SourceTypeID")
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("SourceType");
                });

            modelBuilder.Entity("AgroForecast.Domain.Entities.SavingsLog", b =>
                {
                    b.HasOne("AgroForecast.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgroForecast.Domain.Entities.User", "User")
                        .WithMany("SavingsLogs")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AgroForecast.Domain.Entities.UserFavorite", b =>
                {
                    b.HasOne("AgroForecast.Domain.Entities.Market", "Market")
                        .WithMany()
                        .HasForeignKey("MarketID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgroForecast.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgroForecast.Domain.Entities.User", "User")
                        .WithMany("UserFavorites")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Market");

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AgroForecast.Domain.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("AgroForecast.Domain.Entities.Market", b =>
                {
                    b.Navigation("PriceForecasts");

                    b.Navigation("PriceLogs");
                });

            modelBuilder.Entity("AgroForecast.Domain.Entities.Product", b =>
                {
                    b.Navigation("PriceForecasts");

                    b.Navigation("PriceLogs");

                    b.Navigation("ProductAliases");
                });

            modelBuilder.Entity("AgroForecast.Domain.Entities.SourceType", b =>
                {
                    b.Navigation("PriceLogs");

                    b.Navigation("ProductAliases");
                });

            modelBuilder.Entity("AgroForecast.Domain.Entities.User", b =>
                {
                    b.Navigation("SavingsLogs");

                    b.Navigation("UserFavorites");
                });
#pragma warning restore 612, 618
        }
    }
}
